name: formbuilder
description: "Clean Drag & Drop form builder"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  csv: ^6.0.0
  uuid: ^4.0.0
  gradient_glow_border: ^2.0.2
  reorderables: ^0.6.0
  canvas_kit: ^0.5.2
  flutter_colorpicker: ^1.1.0
  split_view: ^3.2.1
  window_manager: ^0.5.1
  forui: ^0.14.1
  forui_assets: ^0.14.0
  custom_pop_up_menu: ^1.2.4
  flutter_secure_storage: ^9.2.4
  flutter_svg: ^2.2.0
  toastification: ^2.3.0
  easy_url_launcher: ^0.0.7
  shimmer: ^3.0.0
  dio: ^5.4.0
  google_fonts: ^6.3.0
  flutter_dotenv: ^6.0.0
  hugeicons_pro: ^0.0.2
  get: ^4.7.2
  shared_preferences: ^2.5.3
  image_picker: ^1.2.0
  file_picker: ^8.0.3
  pin_code: ^1.0.2
  mesh_gradient: ^1.3.8


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3
  rename_app: ^1.6.5 #flutter pub run rename_app:main all="FormIt"


flutter_launcher_icons:
  image_path: "assets/logo/logo_mobile.png"
  min_sdk_android: 21
  adaptive_icon_foreground: "assets/logo/logo_mobile.png"  # Path to foreground image
  adaptive_icon_background: "#FFFFFF"
  web:
    generate: true
    image_path: "assets/logo/logo.png"
    background_color: "#FFFFFF"  # White background
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/logo/logo.png"
    icon_size: 60
    background_color: "#FFFFFF"  # White background
    theme_color: "#hexcode"
  macos:
    generate: true
    image_path: "assets/logo/logo.png"
  android:
    generate: true
    image_path: "assets/logo/logo_mobile.png"
    color: "#FFFFFF"
    background_color: "#FFFFFF"  # White background
    icon_size: 144  # Adjust this for Android icons

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/logo/
    - assets/vectors/
    - assets/icons/